defmodule Milvex.Milvus.Proto.Common.ObjectPrivilege do
  use Protobuf, enum: true, protoc_gen_elixir_version: "0.15.0", syntax: :proto3

  field :PrivilegeAll, 0
  field :PrivilegeCreateCollection, 1
  field :PrivilegeDropCollection, 2
  field :PrivilegeDescribeCollection, 3
  field :PrivilegeShowCollections, 4
  field :PrivilegeLoad, 5
  field :PrivilegeRelease, 6
  field :PrivilegeCompaction, 7
  field :PrivilegeInsert, 8
  field :PrivilegeDelete, 9
  field :PrivilegeGetStatistics, 10
  field :PrivilegeCreateIndex, 11
  field :PrivilegeIndexDetail, 12
  field :PrivilegeDropIndex, 13
  field :PrivilegeSearch, 14
  field :PrivilegeFlush, 15
  field :PrivilegeQuery, 16
  field :PrivilegeLoadBalance, 17
  field :PrivilegeImport, 18
  field :PrivilegeCreateOwnership, 19
  field :PrivilegeUpdateUser, 20
  field :PrivilegeDropOwnership, 21
  field :PrivilegeSelectOwnership, 22
  field :PrivilegeManageOwnership, 23
  field :PrivilegeSelectUser, 24
  field :PrivilegeUpsert, 25
  field :PrivilegeCreateResourceGroup, 26
  field :PrivilegeDropResourceGroup, 27
  field :PrivilegeDescribeResourceGroup, 28
  field :PrivilegeListResourceGroups, 29
  field :PrivilegeTransferNode, 30
  field :PrivilegeTransferReplica, 31
  field :PrivilegeGetLoadingProgress, 32
  field :PrivilegeGetLoadState, 33
  field :PrivilegeRenameCollection, 34
  field :PrivilegeCreateDatabase, 35
  field :PrivilegeDropDatabase, 36
  field :PrivilegeListDatabases, 37
  field :PrivilegeFlushAll, 38
  field :PrivilegeCreatePartition, 39
  field :PrivilegeDropPartition, 40
  field :PrivilegeShowPartitions, 41
  field :PrivilegeHasPartition, 42
  field :PrivilegeGetFlushState, 43
  field :PrivilegeCreateAlias, 44
  field :PrivilegeDropAlias, 45
  field :PrivilegeDescribeAlias, 46
  field :PrivilegeListAliases, 47
  field :PrivilegeUpdateResourceGroups, 48
  field :PrivilegeAlterDatabase, 49
  field :PrivilegeDescribeDatabase, 50
  field :PrivilegeBackupRBAC, 51
  field :PrivilegeRestoreRBAC, 52
  field :PrivilegeGroupReadOnly, 53
  field :PrivilegeGroupReadWrite, 54
  field :PrivilegeGroupAdmin, 55
  field :PrivilegeCreatePrivilegeGroup, 56
  field :PrivilegeDropPrivilegeGroup, 57
  field :PrivilegeListPrivilegeGroups, 58
  field :PrivilegeOperatePrivilegeGroup, 59
  field :PrivilegeGroupClusterReadOnly, 60
  field :PrivilegeGroupClusterReadWrite, 61
  field :PrivilegeGroupClusterAdmin, 62
  field :PrivilegeGroupDatabaseReadOnly, 63
  field :PrivilegeGroupDatabaseReadWrite, 64
  field :PrivilegeGroupDatabaseAdmin, 65
  field :PrivilegeGroupCollectionReadOnly, 66
  field :PrivilegeGroupCollectionReadWrite, 67
  field :PrivilegeGroupCollectionAdmin, 68
  field :PrivilegeGetImportProgress, 69
  field :PrivilegeListImport, 70
  field :PrivilegeAddCollectionField, 71
  field :PrivilegeAddFileResource, 72
  field :PrivilegeRemoveFileResource, 73
  field :PrivilegeListFileResources, 74
  field :PrivilegeUpdateReplicateConfiguration, 78
  field :PrivilegeCreateSnapshot, 79
  field :PrivilegeDropSnapshot, 80
  field :PrivilegeDescribeSnapshot, 81
  field :PrivilegeListSnapshots, 82
  field :PrivilegeRestoreSnapshot, 83
  field :PrivilegeAlterCollectionSchema, 84
end
